import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Providers } from "@/providers/nextui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default AuthLayout;
